#debug: true

spring:
  application:
    name: shunya-punter

  aop:
    proxy-target-class: true

  mvc:
    ignore-default-model-on-redirect: true

#Hibernate Framework
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/punter?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      username: root
      password: password

  jpa:
     show-sql: false
     database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
     hibernate:
       ddl-auto: none
       use-new-id-generator-mappings: true
#     properties:
#        javax.persistence.sharedCache.mode: ALL
#        hibernate:
#          type: trace
#          cache:
#            use_second_level_cache: true
#            use_query_cache: true
#            region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  resources:
      chain:
          strategy:
                  content:
                        enabled: true
                        paths: /**/*.css, /**/*.png, /**/*.jpg
                  fixed:
                        enabled: true
                        paths: /**/*.js, /**/*.map
                        version: ${application.version}
          enabled: true
          cache: true
          html-application-cache: true
      cache-period: 36000000


#  thymeleaf:
#       cache: false
#       mode: LEGACYHTML5
#       suffix: .html
#       encoding: UTF-8

  freemarker:
       cache: false
       settings:
            template_exception_handler: rethrow
            whitespace_stripping: true
            datetime_format: 'dd.MMM.yyyy HH:mm a'
            time_format: 'HH:mm'
            date_format: 'dd.MMM.yyyy'
            arithmetic_engine: conservative
            classic_compatible: false
            auto_import: spring.ftl as spring
       expose-spring-macro-helpers: true
       content-type: text/html; charset=UTF-8
       allow-request-override: false
       expose-request-attributes: false
       request-context-attribute: rc

  messages:
       basename: i18n/messages

  view:
      prefix: /templates/
      suffix: .ftl

  mail:
      host: smtp.zoho.com
      port: 587
#      port: 465
      username: dev@shunyafoundation.com
      password: service123
      properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
#            mail.smtp.socketFactory.port: 465

  jackson:
      default-property-inclusion: non_null
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 1MB

#Logging Framework
logging:
    level:
      org.springframework:
          security: INFO
          web: INFO
          boot: INFO
      com.shunya: DEBUG
      org.hibernate: ERROR
#      org.hibernate.type: TRACE
    file: logs/${spring.application.name}.log
#    file: ${java.io.tmpdir}/${spring.application.name}.log

#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8999/uaa/oauth/token
      userAuthorizationUri: http://localhost:8999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    auth:
      path: /uaa/**
      strip-prefix: false
      sensitive-headers:
      url: http://localhost:9999
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

#Set timeout for zuul manually so that it does not times out easily.
hystrix:
  command:
    default:
      execution:
        timeout.enabled: false
        isolation.thread.timeoutInMilliseconds: 60000
  threadpool.default:
    coreSize: 5
    maxQueueSize: 100
    queueSizeRejectionThreshold: 100

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

server:
  port: 8989
  compression:
    enabled: true
  display-name: Shunya eLearning App
  undertow:
      io-threads: 3
      worker-threads: 5
  error.whitelabel.enabled: false

custom:
  static:
      path:

file.store.path: C:/Munish


---

spring:
  profiles: test

#Datasource Properties
  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test
#      schema: classpath:/schema.sql

---
spring:
  profiles:
    active: dev