
  CREATE TABLE  TRADING_PROPERTIES  
    (
     TRADING_PROPERTIES_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 FUND_NON_LINEAR_LIMIT  NUMBER(10,0), 
	 FUND_LINEAR_LIMIT  NUMBER(10,0), 
	 MARKET_LIMIT  NUMBER(10,0), 
	 CREDIT_LIMIT  NUMBER(10,0), 
	 HOLDING_ACT_LIMIT  NUMBER(10,0), 
	 LIQUIDITY_INFO  VARCHAR2(255 CHAR), 
	 SETTLEMENT_ID  VARCHAR2(255 CHAR), 
	 TRADING_DEADLINE  VARCHAR2(260)
   )

  CREATE TABLE  CLIENT  
    (	 CLIENT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 CLIENT_NAME  VARCHAR2(255 CHAR), 
	 DISCLAIMER_ID  NUMBER(10,0)
   )

  CREATE TABLE  PRODUCT  
    (	 PRODUCT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 CURRENCY  VARCHAR2(7 CHAR), 
	 DENOMINATION  NUMBER(19,0), 
	 EXPIRY_DATE  DATE, 
	 GR_SYMBOL  VARCHAR2(255 CHAR), 
	 ISIN  VARCHAR2(255 CHAR), 
	 ISSUE_DATE  DATE, 
	 NAME  VARCHAR2(255 CHAR), 
	 PRODUCT_TYPE  VARCHAR2(255 CHAR), 
	 RECALCULATE_PRE_INCEPTION  DATE, 
	 RECALCULATE_POST_INCEPTION  DATE, 
	 SALESPERSON  VARCHAR2(50 CHAR), 
	 STATE  VARCHAR2(50 CHAR), 
	 TRADEABLE_INFO_ID  NUMBER(10,0), 
	 VALOREN  VARCHAR2(50 CHAR), 
	 DISTRIBUTOR_ID  NUMBER(10,0)
   )

  CREATE TABLE  PRODUCT_DELTA_ONE  
    (	 PRODUCT_ID  NUMBER(10,0), 
	 BASIS_POINTS  NUMBER(10,0), 
	 CURRENCY_OVERLAY  NUMBER(1,0), 
	 MULTIPLIER  FLOAT(126), 
	 FUND_FEEDER_ID  NUMBER(10,0)
   )

  CREATE TABLE  PRODUCT_DISCLAIMER  
    (	 DISCLAIMER_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 DISCLAIMER_TEXT  CLOB, 
	 DEFAULT_DISCLAIMER  NUMBER(1,0)
   )

  CREATE TABLE  PRODUCT_INDEX  
    (	 PRODUCT_INDEX_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 BASIS_COEFFICIENT  FLOAT(126), 
	 INDEX_COMMENT  VARCHAR2(255 CHAR), 
	 INDEX_TYPE  VARCHAR2(255 CHAR), 
	 INDEX_VALUE  FLOAT(126), 
	 INDEX_OVERRIDE_VALUE  FLOAT(126), 
	 INDEX_VALUE_DATE  DATE, 
	 INDEX_FINAL  NUMBER(1,0), 
	 CURRENT_NAV  FLOAT(126), 
	 CURRENT_NAV_DATE  DATE, 
	 CURRENT_NAV_FINAL  NUMBER(1,0), 
	 PRODUCT_STATE  VARCHAR2(255 CHAR), 
	 RECORD_START_DATE  DATE, 
	 RECORD_END_DATE  DATE, 
	 UNDERLYING_FUND_ID  NUMBER(10,0), 
	 CALCULATED  NUMBER(1,0), 
	 PRODUCT_ID  NUMBER(10,0)
   )

  CREATE TABLE  PRODUCT_TO_CLIENT  
    (	 PRODUCT_ID  NUMBER(10,0), 
	 CLIENT_ID  NUMBER(10,0)
   )

  CREATE TABLE  COUNTERPARTY  
    (	 TC_CP_ID  NUMBER, 
	 TC_CP_DESCRIPTION  VARCHAR2(75), 
	 TC_CP_REG_NAME  VARCHAR2(75), 
	 TC_CP_REG_ADDRESS  VARCHAR2(255), 
	 TC_CP_CUSTODIAN_NAME  VARCHAR2(75), 
	 TC_CP_CUSTODIAN_FAX  VARCHAR2(15), 
	 TC_CP_GR_ID  VARCHAR2(75), 
	 TC_CP_INACTIVE  VARCHAR2(1) DEFAULT 'N'
   )

  CREATE TABLE  ALERT_COMMENTS  
    (	 AC_COMMENT_ID  NUMBER(10,0), 
	 AC_ALERT_ID  NUMBER(10,0), 
	 AC_COMMENT  VARCHAR2(1024 CHAR), 
	 AC_UPDATED_BY  VARCHAR2(255), 
	 AC_UPDATED_ON  DATE
   )

  CREATE TABLE  EOD_DELETED_ALERTS  
    (	 ALERT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  EOD_DELETED_ALERT_COMMENTS  
    (	 AC_COMMENT_ID  NUMBER(10,0), 
	 AC_ALERT_ID  NUMBER(10,0), 
	 AC_COMMENT  VARCHAR2(1024 CHAR), 
	 AC_UPDATED_BY  VARCHAR2(255), 
	 AC_UPDATED_ON  DATE
   )

  CREATE TABLE  DELETED_ALERTS  
    (	 ALERT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  DELETED_ALERT_COMMENTS  
    (	 AC_COMMENT_ID  NUMBER(10,0), 
	 AC_ALERT_ID  NUMBER(10,0), 
	 AC_COMMENT  VARCHAR2(1024 CHAR), 
	 AC_UPDATED_BY  VARCHAR2(255), 
	 AC_UPDATED_ON  DATE
   )

  CREATE TABLE  TEMP_ALERTS  
    (	 ALERT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  PAYMENT_ALERTS  
    (	 ALERT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  REM_MGM_ALERTS  
    (	 SYMBOL  VARCHAR2(50 CHAR), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 PFM_FEE  NUMBER, 
	 MGMT_FEE  NUMBER, 
	 ALERT_ID  NUMBER(10,0)
   )

  CREATE TABLE  REM_PERF_ALERTS  
    (	 SYMBOL  VARCHAR2(50 CHAR), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 PFM_FEE  NUMBER, 
	 MGMT_FEE  NUMBER, 
	 ALERT_ID  NUMBER(10,0)
   )

  CREATE TABLE  ALERTS  
    (	 ALERT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  AUDITS  
    (	 AUDIT_ID  NUMBER(10,0), 
	 CODE  NUMBER(10,0), 
	 CHANNEL  VARCHAR2(255 CHAR), 
	 SEVERITY  VARCHAR2(255 CHAR), 
	 AS_AT  DATE, 
	 MESSAGE  VARCHAR2(1024 CHAR), 
	 RAISED  TIMESTAMP (6), 
	 RAISED_BY  VARCHAR2(255 CHAR), 
	 OBJECT_ID  NUMBER(10,0), 
	 OBJECT_TYPE  VARCHAR2(255 CHAR), 
	 EXTRA_INFO  CLOB
   )

  CREATE TABLE  CONTACT  
    (	 CONTACT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 TYPE  NUMBER(10,0), 
	 NAME  VARCHAR2(255 CHAR), 
	 TEL  VARCHAR2(255 CHAR), 
	 FAX  VARCHAR2(255 CHAR), 
	 ORGANIZATION_ID  NUMBER(10,0)
   )

  CREATE TABLE  ENUMERATION_VALUE  
    (	 ENUMERATION_VALUE_ID  NUMBER(10,0), 
	 CATEGORY  VARCHAR2(255 CHAR), 
	 VALUE  VARCHAR2(255 CHAR), 
	 VERSION  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FAMILY  
    (	 FUND_FAMILY_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 NAME  VARCHAR2(250 CHAR), 
	 FUND_MANAGER_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEEDER  
    (	 FUND_FEEDER_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 FUND_TYPE  VARCHAR2(20 CHAR), 
	 SYMBOL  VARCHAR2(70 CHAR), 
	 SEDOL  VARCHAR2(40 CHAR), 
	 STATE  VARCHAR2(40 CHAR), 
	 START_DATE  DATE, 
	 END_DATE  DATE, 
	 NAME  VARCHAR2(250 CHAR), 
	 REACCRUAL_FROM  DATE, 
	 TRADE_INFO_ID  NUMBER(10,0), 
	 POST_MGMT_FEES_TO_GR  NUMBER(1,0), 
	 POST_PERF_FEES_TO_GR  NUMBER(1,0), 
	 RELOAD_POSITIONS  NUMBER(1,0), 
	 RELOAD_NAVS  NUMBER(1,0), 
	 FUND_MASTER_ID  NUMBER(10,0), 
	 FEE_CALC_PROPS_ID  NUMBER(10,0), 
	 FEE_PAY_PROPS_ID  NUMBER(10,0), 
	 NAV_PROPS_ID  NUMBER(10,0), 
	 TRADING_PROPS_ID  NUMBER(10,0), 
	 ORGANIZATION_ID  NUMBER(10,0), 
	 PROPERTIES_ID  NUMBER(10,0), 
	 TOGGLE  NUMBER(1,0), 
	 OWNER  VARCHAR2(100 CHAR), 
	 TRADE_INFO_ID_FOR_FUND  NUMBER(10,0), 
	 POST_ACCRUAL_STATE_TO_GR_STATE  NUMBER(10,0) DEFAULT 0, 
	 CHNG_NAV_FREQ_RELOAD_NAV  NUMBER(1,0) DEFAULT 0
   )

  CREATE TABLE  FUND_FEEDER_NAV  
    (	 NAV_ID  NUMBER(10,0), 
	 FROM_DATE  DATE, 
	 TO_DATE  DATE, 
	 NAV_VALUE  FLOAT(126), 
	 NAV_FINAL  NUMBER(1,0), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 ACTUAL_DATE  DATE
   )

  CREATE TABLE  FUND_FEEDER_POSITION  
    (	 POSITION_ID  NUMBER(10,0), 
	 RISK_CLASS  VARCHAR2(40 CHAR), 
	 FROM_DATE  DATE, 
	 TO_DATE  DATE, 
	 POSITION  FLOAT(126), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 NOTIONAL  NUMBER(*,0) DEFAULT 0
   )

  CREATE TABLE  FUND_FEEDER_PROPERTIES  
    (	 PROPERTIES_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 SHARECLASS  VARCHAR2(255 CHAR), 
	 MARKKEY  VARCHAR2(255 CHAR), 
	 DOMICILE  VARCHAR2(255 CHAR), 
	 VOTING_STATUS  NUMBER(10,0), 
	 ISIN_ID  VARCHAR2(255 CHAR), 
	 BLOOMBERG_SYMBOL  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  FUND_FEEDER_RISK_CLASS  
    (	 RISK_CLASS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 RISK_CLASS  VARCHAR2(40 CHAR), 
	 FUND_FEEDER_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_CALC_PROPS  
    (	 FEE_CALC_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 DAY_BASIS  VARCHAR2(40 CHAR), 
	 FX_RATE_BASIS  VARCHAR2(40 CHAR), 
	 NAV_BASIS  VARCHAR2(40 CHAR), 
	 MGMT_FEE_ALGORITHM  VARCHAR2(40 CHAR), 
	 MGMT_FEE  FLOAT(126), 
	 MGMT_FEE_REBATE  FLOAT(126), 
	 PERF_FEE_ALGORITHM  VARCHAR2(40 CHAR), 
	 PERF_FEE  FLOAT(126), 
	 PERF_FEE_REBATE  FLOAT(126), 
	 PERF_FEE_FULCRUM_FACTOR  FLOAT(126), 
	 PERF_FEE_HURDLE  FLOAT(126), 
	 PERF_FEE_MAXIMUM_FEE  FLOAT(126)
   )

  CREATE TABLE  FUND_FEE_CALC_PROPS_H  
    (	 FEE_CALC_PROPS_H_ID  NUMBER(10,0), 
	 FEE_CALC_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 DAY_BASIS  VARCHAR2(40 CHAR), 
	 FX_RATE_BASIS  VARCHAR2(40 CHAR), 
	 NAV_BASIS  VARCHAR2(40 CHAR), 
	 MGMT_FEE_ALGORITHM  VARCHAR2(40 CHAR), 
	 MGMT_FEE  FLOAT(126), 
	 MGMT_FEE_REBATE  FLOAT(126), 
	 PERF_FEE  FLOAT(126), 
	 PERF_FEE_REBATE  FLOAT(126), 
	 PERF_FEE_ALGORITHM  VARCHAR2(40 CHAR), 
	 PERF_FEE_FULCRUM_FACTOR  FLOAT(126), 
	 PERF_FEE_HURDLE  FLOAT(126), 
	 PERF_FEE_MAXIMUM_FEE  FLOAT(126)
   )

  CREATE TABLE  FUND_FEE_DAILY_ACCRUAL  
    (	 FUND_FEE_DAILY_ACCRUAL_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 ACCRUAL_DATE  DATE, 
	 ACCRUED_MGMT_FEE  FLOAT(126), 
	 MGMT_FEE_FX_RATE  FLOAT(126), 
	 MGMT_FEE_FX_RATE_STATE  VARCHAR2(40 CHAR), 
	 ACCRUED_PERF_FEE  FLOAT(126), 
	 PERF_FEE_FX_RATE  FLOAT(126), 
	 PERF_FEE_FX_RATE_STATE  VARCHAR2(40 CHAR), 
	 NAV  FLOAT(126), 
	 NAV_STATE  VARCHAR2(40 CHAR), 
	 POSITION  FLOAT(126), 
	 RECORD_START_DATE  DATE, 
	 RECORD_END_DATE  DATE, 
	 RISK_CLASS  VARCHAR2(40 CHAR), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 FEE_CALC_PROPS_H_ID  NUMBER(10,0), 
	 FEE_PAYMENT_PROPS_H_ID  NUMBER(10,0), 
	 NAV_PROPS_H_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_MONTHLY_SUMMARY  
    (	 FUND_FEE_MONTHLY_SUMMARY_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 START_DATE  DATE, 
	 END_DATE  DATE, 
	 RISK_CLASS  VARCHAR2(40 CHAR), 
	 ACCRUED_MGMT_FEE  FLOAT(126), 
	 ACTUAL_MGMT_FEE  FLOAT(126), 
	 ACCRUED_MGMT_FEE_DOLLARS  FLOAT(126), 
	 ACTUAL_MGMT_FEE_DOLLARS  FLOAT(126), 
	 ACCRUED_PERF_FEE  FLOAT(126), 
	 ACTUAL_PERF_FEE  FLOAT(126), 
	 ACCRUED_PERF_FEE_DOLLARS  FLOAT(126), 
	 ACTUAL_PERF_FEE_DOLLARS  FLOAT(126), 
	 NOTIONAL_POSITION  FLOAT(126), 
	 NOTIONAL_POSITION_DOLLARS  FLOAT(126)
   )

  CREATE TABLE  FUND_FEE_PAYMENT  
    (	 FUND_FEE_PAYMENT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 FUND_FEEDER_ID  NUMBER(10,0), 
	 PERIOD_START_DATE  DATE, 
	 PERIOD_END_DATE  DATE, 
	 PAYMENT_TYPE  VARCHAR2(40 CHAR), 
	 PAYMENT_STATE  VARCHAR2(40 CHAR), 
	 NAME  VARCHAR2(250 CHAR), 
	 ACTUAL_FEE  FLOAT(126), 
	 ACCRUAL_STATE  VARCHAR2(40 CHAR), 
	 POST_TO_GR  NUMBER(1,0), 
	 POSTED_TO_GR_DATE  DATE, 
	 PAYMENT_DATE  DATE, 
	 SETTLEMENT_DATE  DATE, 
	 MIGRATION_REQUIRED  NUMBER(1,0), 
	 PAYMENT_CURRENCY  VARCHAR2(7 CHAR)
   )

  CREATE TABLE  FUND_FEE_PAYMENT_COMMENT  
    (	 FUND_FEE_PAYMENT_COMMENT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 AUTHOR  VARCHAR2(40 CHAR), 
	 MESSAGE  VARCHAR2(4000 CHAR), 
	 POSTED  TIMESTAMP (6), 
	 PAYMENT_STATE  VARCHAR2(40 CHAR), 
	 FUND_FEE_PAYMENT_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_PAYMENT_PROPS  
    (	 FEE_PAYMENT_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 MGMT_FEE_CURRENCY  VARCHAR2(7 CHAR), 
	 MGMT_FEE_FREQUENCY  VARCHAR2(40 CHAR), 
	 PERF_FEE_CURRENCY  VARCHAR2(7 CHAR), 
	 PERF_FEE_FREQUENCY  VARCHAR2(40 CHAR), 
	 CALENDAR  VARCHAR2(40 CHAR), 
	 DAY_CONVENTION  VARCHAR2(40 CHAR), 
	 STALE_AFTER  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_PAYMENT_PROPS_H  
    (	 FEE_PAYMENT_PROPS_H_ID  NUMBER(10,0), 
	 FEE_PAYMENT_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 MGMT_FEE_CURRENCY  VARCHAR2(7 CHAR), 
	 MGMT_FEE_FREQUENCY  VARCHAR2(40 CHAR), 
	 PERF_FEE_CURRENCY  VARCHAR2(7 CHAR), 
	 PERF_FEE_FREQUENCY  VARCHAR2(40 CHAR), 
	 CALENDAR  VARCHAR2(40 CHAR), 
	 DAY_CONVENTION  VARCHAR2(40 CHAR), 
	 STALE_AFTER  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_PAYMENT_SUMMARY  
    (	 FUND_FEE_PAYMENT_ID  NUMBER(10,0), 
	 FUND_FEE_MONTHLY_SUMMARY_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_FEE_RISK_CLASS_PAYMENT  
    (	 FUND_FEE_RISK_CLASS_PAYMENT_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 RISK_CLASS  VARCHAR2(40 CHAR), 
	 ACTUAL_FEE  FLOAT(126), 
	 FUND_FEE_PAYMENT_ID  NUMBER(10,0)
   )

  CREATE TABLE  FUND_MANAGER  
    (	 FUND_MANAGER_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 NAME  VARCHAR2(250 CHAR), 
	 ROOT  VARCHAR2(20 CHAR)
   )

  CREATE TABLE  FUND_MASTER  
    (	 FUND_MASTER_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 NAME  VARCHAR2(250 CHAR), 
	 FUND_FAMILY_ID  NUMBER(10,0), 
	 DISCLAIMER_ID  NUMBER
   )

  CREATE TABLE  FUND_NAV_PROPS  
    (	 NAV_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 CALENDAR  VARCHAR2(40 CHAR), 
	 CURRENCY  VARCHAR2(7 CHAR), 
	 DAY_CONVENTION  VARCHAR2(40 CHAR), 
	 ESTIMATE_FREQUENCY  VARCHAR2(20 CHAR), 
	 FINAL_FREQUENCY  VARCHAR2(20 CHAR), 
	 STALE_AFTER  NUMBER(10,0)
   )

  CREATE TABLE  FUND_NAV_PROPS_H  
    (	 NAV_PROPS_H_ID  NUMBER(10,0), 
	 NAV_PROPS_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 CALENDAR  VARCHAR2(40 CHAR), 
	 CURRENCY  VARCHAR2(7 CHAR), 
	 DAY_CONVENTION  VARCHAR2(40 CHAR), 
	 ESTIMATE_FREQUENCY  VARCHAR2(20 CHAR), 
	 FINAL_FREQUENCY  VARCHAR2(20 CHAR), 
	 STALE_AFTER  NUMBER(10,0)
   )

  CREATE TABLE  FX_RATE  
    (	 FX_RATE_ID  NUMBER(10,0), 
	 VALUE_DATE  DATE, 
	 CURRENCY  VARCHAR2(255 CHAR), 
	 RATE  FLOAT(126)
   )

  CREATE TABLE  NINETY_DAY_TBILL  
    (	 TBILL_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 FROM_DATE  DATE, 
	 TO_DATE  DATE, 
	 RATE  FLOAT(126), 
	 FUND_FEEDER_ID  NUMBER(10,0)
   )

  CREATE TABLE  ORGANIZATION  
    (	 ORGANIZATION_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 EMAIL  VARCHAR2(255 CHAR), 
	 ADDRESS1  VARCHAR2(255 CHAR), 
	 ADDRESS2  VARCHAR2(255 CHAR), 
	 ADDRESS3  VARCHAR2(255 CHAR), 
	 ADDRESS4  VARCHAR2(255 CHAR), 
	 POSTCODE  VARCHAR2(255 CHAR), 
	 WEB  VARCHAR2(255 CHAR), 
	 ADMIN_CONTACT_NAME  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  PERSISTENT_EVENTS  
    (	 PERSISTENT_EVENT_ID  NUMBER(10,0), 
	 XML_EVENT  CLOB, 
	 STATE  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  PROCESS_STATUS  
    (	 PROCESS_STATUS_ID  NUMBER(10,0), 
	 NAME  VARCHAR2(255 CHAR), 
	 LAST_RAN  TIMESTAMP (6), 
	 AS_AT  DATE, 
	 STATE  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  SECURITY_PERMISSION  
    (	 SECURITY_PERMISSION_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 TYPE  VARCHAR2(255 CHAR), 
	 KEY  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  SECURITY_ROLE  
    (	 SECURITY_ROLE_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 NAME  VARCHAR2(255 CHAR)
   )

  CREATE TABLE  SECURITY_ROLE_PERMISSION  
    (	 SECURITY_PERMISSION_ID  NUMBER(10,0), 
	 SECURITY_ROLE_ID  NUMBER(10,0)
   )

  CREATE TABLE  SECURITY_SESSION  
    (	 SESSION_ID  VARCHAR2(255 CHAR), 
	 CREATED  DATE, 
	 SECURITY_USER_ID  NUMBER(10,0)
   )

  CREATE TABLE  SECURITY_USER  
    (	 SECURITY_USER_ID  NUMBER(10,0), 
	 VERSION  NUMBER(10,0), 
	 NAME  VARCHAR2(255 CHAR), 
	 USERNAME  VARCHAR2(255 CHAR), 
	 EPASSWORD  VARCHAR2(255 CHAR), 
	 GPIN  NUMBER(10,0)
   )

  CREATE TABLE  SECURITY_USER_ROLE  
    (	 SECURITY_ROLE_ID  NUMBER(10,0), 
	 SECURITY_USER_ID  NUMBER(10,0)
   )
