SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('INDEX')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('VIEW')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('TRIGGER')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('FUNCTION')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('PROCEDURE')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME  FROM USER_OBJECTS  WHERE OBJECT_TYPE IN ('SEQUENCE')
UNION ALL
SELECT 'DROP ' || OBJECT_TYPE || ' ' || OBJECT_NAME ||' CASCADE CONSTRAINTS' FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE'